name: Issue checker

on:
  issues:
    types: [labeled]

jobs:
  close-invalid-app-compat-report:
    name: Close invalid app compatibility report
    runs-on: ubuntu-latest
    if: |
      github.event.label.name == 'specific-app/site-related :iphone:' && 
      github.event.issue.title == '[app name] compatibility report'
    steps:
      - name: Add title reword comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello @${{ github.event.issue.user.login }}
            
            It looks like you left the default report title.
            Thanks to update it to with the application name.
            
            Regards
